FROM openjdk:8-jdk
VOLUME /tmp
COPY /target/spring-boot-docker-image.jar spring-boot-docker-image.jar
CMD [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /spring-boot-docker-image.jar" ]