name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      -name: Build
      run: mvn -B package --file pom.xml
      -name: Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:login
      -name: Push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
      -name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}