# This workflow will perform tests of our code

# Event that triggers this workflow
on:
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      PORT: 8080
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
      - name: Test with Maven
        run: mvn -B test --file pom.xml
